
project_id = "d58cd666-4e5b-417f-9d6f-783e99b07fb6"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.send-notifications]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false
