// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkeicfcxowshfhipkmfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rZWljZmN4b3dzaGZoaXBrbWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTM4NjEsImV4cCI6MjA2NTQ2OTg2MX0.OWY6uFvJxbZXjh_HpEkcvWqCGXmBfsbfaHI5XyxrJOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);